### PR TITLE
Fix #777: Support non-enumerable props when stubbing objects

### LINKED ISSUE #777: Proposal: Stub non-enumerable properties when only object is given
Using sinon v1.15.3, the following code snippet does not work

```javascript
class Foo {
  doSomething() {
    var thing = 0;
    // do stuff with thing...
    return thing;
  }
}

const fooStub = sinon.createStubInstance(Foo);
fooStub.doSomething.returns(1);
```

The last line throws a `TypeError`, saying that `doSomething` does not have a `returns` method. This is due to the fact that function defined in class expressions are attached as [non-enumerable properties](http://www.ecma-international.org/ecma-262/6.0/#sec-runtime-semantics-classdefinitionevaluation) (see step 21.a), but [within sinon.stub](https://github.com/cjohansen/Sinon.JS/blob/master/lib/sinon/stub.js#L51-L55) a `for..in` loop is used, meaning any non-enumerable property is excluded. 

I think it would help with the future-forwardness of sinon to use something like `Object.getOwnPropertyNames` instead of `for..in` when using stub with only an object, because it would allow `createStubInstance` to interop seamlessly with class definitions, and I would be happy to submit a PR for this. I was just wondering if there are any arguments against stubbing non-enumerable properties and if so what would be a good solution to allow stubbing them in certain cases?

### PR DESCRIPTION
**Pull request by traviskaufman**
This commit modifies sinon.stub() such that when only an object is
given, all non-enumerable properties as well as enumerable properties
that are functions will be stubbed.

The iteration over the object is accomplished by using sinon.walk, a new
utility function that supports iterating over all properties of an
object up the prototype chain, falling back to for..in when
getOwnPropertyNames is not available.

This functionality allows sinon.stub() - and especially methods like
sinon.createStubInstance() - to be future-forward by facilitating the
fact that methods defined in class declarations are non-enumerable by
default. It also allows stubbing of native objects such as Arrays and
Dates without having to explictly pass property names.

### CODE REVIEW

**Comment by traviskaufman** [comment]
:( This is failing because of how PhantomJS 1.9.8 deals with object enumeration. I will look into it and see if I can make the tests more robust.

**Comment by traviskaufman** [comment]
@mantoni @cjohansen possible to get some eyes on these changes?

File: test/walk-test.js [hunk 1]
```diff
@@ -0,0 +1,126 @@
...
+                Target = function Target() {
+                    this.hello = "world";
+                },
+                target = new Target(),
+                rcvr = {},
+                iterator = sinon.spy(),
+                err = null,
+                numCalls = 0,
+                placeholder; // eslint-disable-line no-unused-vars
+
```
Comment (cjohansen) [inline test/walk-test.js]: Nitpicking, but I prefer indvidual vars

Comment (traviskaufman) [inline test/walk-test.js]: No problem. I noticed in some of the other tests the vars are grouped this way, which is the reason I opted for it. Would you prefer individual var decls throughout all the tests?

Comment (cjohansen) [inline test/walk-test.js]: Sloppy reviewing on my end then probably :) I would prefer individual declarations.

Comment (mroderick) [inline test/walk-test.js]: I'll update the `.eslintrc` to only allow individual `var` statements

Comment (mroderick) [inline test/walk-test.js]: I've created #809 to update `.eslintrc` so ESLint will give better feedback about this.

**Comment by nii236** [comment]
This will allow ES2015 classes to be stubbed out correctly, yes? Until the pull request goes through will there be an alternative workaround?

**Comment by mantoni** [comment]
@nii236 This PR can't be merged. Please rebase.

**Comment by traviskaufman** [comment]
@mantoni @nil236 yeah sorry for the delay here, starting a new job and whatnot I've been really busy. I'll re base and re-submit when I get home tonight.

**Comment by nii236** [comment]
@traviskaufman: Thanks! I look forward to it!

**Comment by traviskaufman** [comment]
@mantoni @mroderick made all the changes but the current build failed

```
Error: PhantomJS 1.9.8, Linux | sinon.FakeXMLHttpRequest | .setResponseHeaders | does not call readyStateChange if sync
  Error: INVALID_STATE_ERR - 4
    at verifyRequestOpened (./pkg/sinon.js:4928)
      at setResponseHeaders (./pkg/sinon.js:5144)
      at ./test/util/fake-xml-http-request-test.js:519
Running 1490 tests in 1 runtime ... 88% done
```

It passed for me on my local machine, so this looks like a false negative. Would one of you mind rebuilding?

**Comment by mantoni** [comment]
Nice work! Thank you :+1:

**Comment by nii236** [comment]
Thanks! :+1:

**Comment by traviskaufman** [comment]
np! Thanks for merging!
